import { Press_Start_2P, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";

const pressStart2P = Press_Start_2P({ subsets: ["latin"], weight: "400" });
const IBMPlexMono = IBM_Plex_Mono({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Donate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${pressStart2P.className} ${IBMPlexMono.className}`}>{children}</body>
    </html>
  );
}
